home:
    pattern: /
    controller: Category
topic:
    pattern: /topic/(*path)/(id)
    controller: Topic
topic_new:
    pattern: /topic/new
    controller: Topic
    action:
        get: NewController
    variables:
        layout: edit

post:
    pattern: /post(/id)
    controller: Post

category:
    pattern: /category/(*path)(/page)
    controller: Category

login:
    pattern: /github/login
    controller: User
    action:
        '*': LoginController

logout:
    pattern: /github/logout
    controller: User
    action:
        '*': LogoutController
